### ISSUE TITLE
Thumbnails are buggy!

### ISSUE THREAD

**Issue by aadrian** [addsict/real-world-plantuml#2] opened 2018-01-31 13:41 UTC
Hi,

It seems that some of the thumbnails are strange, i.e. they don't show (in a scaled version) what's in the diagram itself.
e.g. **thumbnail in the middle**:
![puml_bug_1_1](https://user-images.githubusercontent.com/140953/35625985-8993afd6-0694-11e8-9ae8-59d325bda5de.png)

and **when clicked**:
![puml_bug_1_2](https://user-images.githubusercontent.com/140953/35625990-8d6e8a36-0694-11e8-9643-da120bec809e.png)

**Comment by yfuruyama** [comment] 2018-02-03 10:51
Thank you for reporting!

I found the way to reproduce it:

1. Click a thumbnail and open the modal window.
2. Close the modal window.
3. Narrow browser window gradually, and in some point all of `<rect>` tags are disappeared and not rendered.

I've investigated for a while, but unfortunately I couldn't find a root cause.
I'll investigate this more later.

**Comment by yfuruyama** [comment] 2018-12-24 09:57
Fixed by https://github.com/yfuruyama/real-world-plantuml/pull/3

**Closed as completed by yfuruyama** 2018-12-24 09:57 UTC
